### ISSUE TITLE
How to initiate the project?

### ISSUE THREAD

**Issue by alexc-l** [zzsfornlp/zmsp#1]
Hi! Thank you for your code! I was trying to replicate your work in "An Empirical Investigation of Structured Output Modeling for Graph-based Neural Dependency Parsing". But after I prepared my own data, and made a running script as you suggested in "v1/docs/emp_graph.md", the program seemed unable to find the module "msp".
I also noticed that "v1/docs/run.md" says "the main dir zmsp should be in sys.path", but I can't figure out what that means.
Here's my script to run the project, and the error reported.
```
#!/usr/bin/env bash
# =====
# base options
base_opt="conf_output:_conf partype:graph init_from_pretrain:1 lrate.val:0.001 drop_embed:0.33 dropmd_embed:0.33 singleton_thr:2 fix_drop:1 max_epochs:300"
global_unproj_m="dec_algorithm:unproj output_normalizing:global"
# possible losses
prob_loss="loss_function:prob margin.init_val:0."

# =====
# specify paths
SRC_DIR=../v1/
method=${global_unproj_m}
loss=${prob_loss}
# further specify `train/dev/test/embed` paths
DATA_TRAIN="data/2.7UD_English-EWT/en_ewt-ud-train.conllu"
DATA_DEV="data/2.7UD_English-EWT/en_ewt-ud-dev.conllu"
DATA_TEST="data/2.7UD_English-EWT/en_ewt-ud-test.conllu"
DATA_EMBED="data/wiki.en.vec"
# =====
# running
# on GPU 0
CUDA_VISIBLE_DEVICES=0 PYTHONPATH=${SRC_DIR} python3 v1/tasks/cmd.py zdpar.main.train train:${DATA_TRAIN} dev:${DATA_DEV} test:${DATA_TEST} pretrain_file:${DATA_EMBED} device:0 ${base_opt} ${method} ${loss}

```
![image](https://user-images.githubusercontent.com/85003873/193039282-c1b0a9c4-050d-43e9-b5ea-965e69b8d544.png)
Could do tell me how to fix this? Thanks!

**Comment by zzsfornlp** [comment]
Hi, it seems that in your running the "PYTHONPATH" is not set correctly. Since in the script it is set ot a relative path of "../v1/", probably this is not correctly set according to you current working dir. You can try setting it to absolute path, for example: `SRC_DIR=/home/(USERNAME and others)/zmsp/v1`

**Comment by alexc-l** [comment]
It worked! Thank you!!
